@apiAuth = http://localhost:3100/api/v1/auth
@apiAuthReNewToken = http://localhost:3100/api/v1/auth-refresh-token
@apiUser = http://localhost:3100/api/v1/auth/user/marlon
@apiConfig = http://localhost:3100/api/v1/auth/configuration/1

@apiProduct = http://localhost:3100/api/v1/product
@apiCatalog = http://localhost:3100/api/v1/catalogs

@ACCESS_JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5hbWUiOiJtYXJsb24iLCJpYXQiOjE3MTU4Mjg3OTAsImV4cCI6MTcxNTg3MTk5MH0.zbhxmiXot50UbzezqRSELMv45_7lfZzGWHWIq6tFJVM
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5hbWUiOiJtYXJsb24iLCJpYXQiOjE3MTU4Mjg3OTAsImV4cCI6MTcxNTg3MTk5MH0.zbhxmiXot50UbzezqRSELMv45_7lfZzGWHWIq6tFJVM"
@ACCESS_JWT_REFRESH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5hbWUiOiJtYXJsb24iLCJpYXQiOjE3MTU4Mjg3OTAsImV4cCI6MTc0NzM4NjM5MH0.SyCAW5qV85TfJmfPZTeuTC2fRvuA5PYJWyOb_JDqCBM
//GET {{apiUser}}
//Content-Type: application/json
//Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5hbWUiOiJtYXJsb24iLCJpYXQiOjE3MTUwNDk2NDMsImV4cCI6MTcxNTA5Mjg0M30.NSuHDjmRqlHX7dHicPacNZF7_B1R5pUGzBEqErd5jMA


### GET
GET {{apiAuth}}

### Post
POST {{apiAuth}}
Content-Type: application/json

{
    "user": "marlon",
    "password": "marlon01"
}

### Post renewToken
POST {{apiAuthReNewToken}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5hbWUiOiJtYXJsb24iLCJpYXQiOjE3MTU4Mjg3OTAsImV4cCI6MTc0NzM4NjM5MH0.SyCAW5qV85TfJmfPZTeuTC2fRvuA5PYJWyOb_JDqCBM"
}

### Get configurations
GET {{apiConfig}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### POST Products
POST {{apiProduct}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

{
    "Id": 1058,
    "Codigo": "1058",
    "Descripcion": "ATOMIZADORLT JARDI HOGAR",
    "IdClase": 2,
    "IdSubClase": 2,
    "IdUnidad": 27,
    "IdEmpaque": 12,
    "Proveedor": 23,
    "PrecioCostoUSD": 3.18,
    "PrecioCostoCOR": 115,
    "pvpc": 150,
    "pvdc": 128,
    "pvpu": 4.15,
    "pvdu": 3.54,
    "Impuesto": 0,
    "IdEstado": 0,
    "PrecioMinimoVenta": 123.05,
    "PrecioVentaDistribuidor": 11.3,
    "PrecioVentaPublico": 30.43,
    "PrecioMinimoVentaUSD": 3.4,
    "PrcPrecioMinimoVenta": 7
}

### GET Products
GET {{apiProduct}}?limit=30&page=1&sortBy=desc&filter=regproveedor&keyword=1
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### GET Products
GET {{apiProduct}}/818
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### GET Products
DELETE {{apiProduct}}/817
Content-Type: application/json
Authorization: {{ACCESS_JWT}}


### Get Catalogs
GET {{apiCatalog}}/clase?ultimaFechaSincro=03032024104534
Content-Type: application/json
Authorization: {{ACCESS_JWT}}