@apiAuth = http://localhost:3100/api/v1/auth
@apiAuthReNewToken = http://localhost:3100/api/v1/auth-refresh-token
@apiUser = http://localhost:3100/api/v1/auth/user/marlon
@apiConfig = http://localhost:3100/api/v1/auth/configuration/1

@apiProduct = http://localhost:3100/api/v1/product
@apiCatalog = http://localhost:3200/api/v1/catalogs
@apiPriceBranch = http://localhost:3100/api/v1/price-branch
@apiClient = http://localhost:3100/api/v1/client
@apiOrder = http://localhost:3200/api/v1/order
@apiOrderDet = http://localhost:3200/api/v1/order-det

@ACCESS_JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5hbWUiOiJtYXJsb24iLCJpYXQiOjE3MzI1NDMyNjUsImV4cCI6MTczMjU4NjQ2NX0.77SodiKronxB0ZQyZgKOLVMJVOuiOc8xLip5smXADiA

@ACCESS_JWT_REFRESH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5hbWUiOiJtYXJsb24iLCJpYXQiOjE3MTU4Mjg3OTAsImV4cCI6MTc0NzM4NjM5MH0.SyCAW5qV85TfJmfPZTeuTC2fRvuA5PYJWyOb_JDqCBM

@FECHASINCRO = 0

### GET
GET {{apiAuth}}

### Post
POST {{apiAuth}}
Content-Type: application/json

{
    "user": "marlon",
    "password": "marlon01"
}

### Post renewToken
POST {{apiAuthReNewToken}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5hbWUiOnsiSWQiOjEsIkVtcHJlc2FJRCI6MSwiQ29kaWdvIjoibWFybG9uIiwiQ2xhdmUiOiJtYXJsb24wMSIsIk5vbWJyZXMiOiJNYXJsb24gIiwiQXBlbGxpZG9zIjoiRm9uc2VjYSIsIkZlY2hhU2luY3Jvbml6YWNpb24iOjMxMDUyMDI0MTY1MDMwMTAwfSwiaWF0IjoxNzIwMjQ1NjUzLCJleHAiOjE3NTE4MDMyNTN9.kEI_jZ99-Mj2AcC2HTIGi5p28rfvqKBdg3fgHPipJ0s"
}

### Get user
GET {{apiUser}}?fechaSincro={{FECHASINCRO}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}


### Get configurations
GET {{apiConfig}}?fechaSincro={{FECHASINCRO}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### POST Products
POST {{apiProduct}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

{
    "Id": 0,
    "Codigo": "IOS0003459",
    "Descripcion": "Iphone 12 Pro Max",
    "IdClase": 2,
    "IdSubClase": 2,
    "IdUnidad": 27,
    "IdEmpaque": 12,
    "Proveedor": 23,
    "Impuesto": 1,
    "IdEstado": 1
}

### GET Products
GET {{apiProduct}}?limit=100&page=1&sortBy=desc&fechaSincro={{FECHASINCRO}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### GET Products
GET {{apiProduct}}/1059
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### GET Products
DELETE {{apiProduct}}/818
Content-Type: application/json
Authorization: {{ACCESS_JWT}}


### Get Catalogs
GET {{apiCatalog}}/vendedor?fechaSincro={{FECHASINCRO}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### Get Catalogs agencia-usuario/
GET {{apiCatalog}}/agencia-usuario/1?fechaSincro={{FECHASINCRO}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### Get Catalogs facturas-usuario/
GET {{apiCatalog}}/facturas-usuario/89?fechaSincro={{FECHASINCRO}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### Get Catalogs tipos-facturas/
GET {{apiCatalog}}/tipo_factura?fechaSincro={{FECHASINCRO}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### Get Prices
GET {{apiPriceBranch}}?page=1&limit=10&fechaSincro={{FECHASINCRO}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}


### POST Prices
POST {{apiPriceBranch}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

{
    "Id": 0,
    "AgenciaId": 1,
    "TipoPrecioId": 1,
    "ProductoId": 1059,
    "MonedaId": 1,
    "Precio": 355.67,
    "Activo": "true"
}

### GET Prices
GET {{apiPriceBranch}}?limit=20&page=1&fechaSincro=20240629033919443
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### GET Price by Id
GET {{apiPriceBranch}}/1
Content-Type: application/json
Authorization: {{ACCESS_JWT}}


### GET Clients
GET {{apiClient}}?limit=20&page=1&fechaSincro=20240705213813877
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### POST Client
POST {{apiClient}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

{
    "Id": 135,
    "Nombre": "Constructora Nic",
    "Codigo": "CT-003",
    "Identificacion": "801130663",
    "Direccion": "Avenia 35 calle 345",
    "Telefono": "89898989",
    "Correo": "nicconstruccion@gmail.com",
    "IdTipoCliente": 1,
    "IdTipoId": 1,
    "NegRegistro": 0,
    "VendREgistro": 1,
    "DepRegistro": 12,
    "MunRegistro": 23,
    "Saldo": 100.34,
    "Estado": 1
}

### GET Orders
GET {{apiOrder}}?limit=20&page=1&fechaSincro=20240705213813877
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### POST Order
POST {{apiOrder}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

{
    "Id": "1",
    "NumeroPedido": "PD-1021225",
    "NumeroFactura": "FT-1021225",
    "VendedorID": 1,
    "ClienteID": 1,
    "UsuarioID": 1,
    "AgenciaID": 1,
    "EstadoID": 1,
    "FacturaID": 1,
    "TipoFacturaID": 1,
    "MonedaID": 1,
    "UsuarioEstadoID": 1,
    "Direccion": "Avenia 35 calle 345",
    "NombreCliente": "Marlon Jose Fonseca Garcia",
    "SubTotal": 100.00,
    "Impuesto": 10.00,
    "Retencion": 0.00,
    "Total": 110.00,
    "DiasCredito": 0,
    "TipoCambio": 36.5,
    "NumFechaEstado": 0,
    "Saldo": 100.34,
    "Estado": 1
}


### GET Orders-Det
GET {{apiOrderDet}}?limit=20&page=1&fechaSincro=20240705213813877&filter=PedidoID&keyword=1
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### POST Order-Det
POST {{apiOrderDet}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

{
    "PedidoID": 1,
    "ProductoID": 1,
    "Cantidad": 1,
    "Precio": 100.00,
    "SubTotal": 100.00,
    "IGV": 10.00,
    "Total": 110.00
}