@apiAuth = http://localhost:3100/api/v1/auth
@apiAuthReNewToken = http://localhost:3100/api/v1/auth-refresh-token
@apiUser = http://localhost:3100/api/v1/auth/user/marlon
@apiConfig = http://localhost:3100/api/v1/auth/configuration/1

@apiProduct = http://localhost:3100/api/v1/product
@apiCatalog = http://localhost:3100/api/v1/catalogs
@apiPriceBranch = http://localhost:3100/api/v1/price-branch
@apiClient = http://localhost:3100/api/v1/client

@ACCESS_JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5hbWUiOiJtYXJsb24iLCJpYXQiOjE3MjAyOTkwNTMsImV4cCI6MTcyMDM0MjI1M30.pinrSbOhgGj8-rtLtmKriei9v93WDdtVtzqYYtataiI

@ACCESS_JWT_REFRESH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5hbWUiOiJtYXJsb24iLCJpYXQiOjE3MTU4Mjg3OTAsImV4cCI6MTc0NzM4NjM5MH0.SyCAW5qV85TfJmfPZTeuTC2fRvuA5PYJWyOb_JDqCBM

@FECHASINCRO = 0

### GET
GET {{apiAuth}}

### Post
POST {{apiAuth}}
Content-Type: application/json

{
    "user": "marlon",
    "password": "marlon01"
}

### Post renewToken
POST {{apiAuthReNewToken}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5hbWUiOiJtYXJsb24iLCJpYXQiOjE3MTU4Mjg3OTAsImV4cCI6MTc0NzM4NjM5MH0.SyCAW5qV85TfJmfPZTeuTC2fRvuA5PYJWyOb_JDqCBM"
}

### Get user
GET {{apiUser}}?fechaSincro={{FECHASINCRO}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}


### Get configurations
GET {{apiConfig}}?fechaSincro={{FECHASINCRO}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### POST Products
POST {{apiProduct}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

{
    "Id": 0,
    "Codigo": "IOS0003459",
    "Descripcion": "Iphone 12 Pro Max",
    "IdClase": 2,
    "IdSubClase": 2,
    "IdUnidad": 27,
    "IdEmpaque": 12,
    "Proveedor": 23,
    "Impuesto": 1,
    "IdEstado": 1
}

### GET Products
GET {{apiProduct}}?limit=100&page=1&sortBy=desc&fechaSincro={{FECHASINCRO}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### GET Products
GET {{apiProduct}}/1059
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### GET Products
DELETE {{apiProduct}}/818
Content-Type: application/json
Authorization: {{ACCESS_JWT}}


### Get Catalogs
GET {{apiCatalog}}/tipo_identificacion?fechaSincro={{FECHASINCRO}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}


### Get Prices
GET {{apiPriceBranch}}?page=1&limit=10&fechaSincro={{FECHASINCRO}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}


### POST Prices
POST {{apiPriceBranch}}
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

{
    "Id": 0,
    "AgenciaId": 1,
    "TipoPrecioId": 1,
    "ProductoId": 1059,
    "MonedaId": 1,
    "Precio": 355.67,
    "Activo": "true"
}

### GET Prices
GET {{apiPriceBranch}}?limit=20&page=1
Content-Type: application/json
Authorization: {{ACCESS_JWT}}

### GET Price by Id
GET {{apiPriceBranch}}/1
Content-Type: application/json
Authorization: {{ACCESS_JWT}}


### GET Clients
GET {{apiClient}}?limit=20&page=1
Content-Type: application/json
Authorization: {{ACCESS_JWT}}